---
- name: Install Gunicorn
  pip:
        chdir={{ gunicorn_app_dir }}
        name=gunicorn
        virtualenv=venv
  register: gunicorninstalled

- name: Create Template Configuration
  when: gunicorninstalled|success
  template: 
        src=gunicorn.py.j2
        dest={{ gunicorn_app_dir }}/gunicorn.py
  notify:
        - Start Gunicorn


